// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVyry1qKqTFuyZvWaXH9Z2Gv2zsQKEDZw',
    appId: '1:160463287371:web:09219fb0f6fc5c181989ce',
    messagingSenderId: '160463287371',
    projectId: 'dayzoff-c2455',
    authDomain: 'dayzoff-c2455.firebaseapp.com',
    storageBucket: 'dayzoff-c2455.appspot.com',
    measurementId: 'G-732M2BEFVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNNhq-ZZv5JPv_m_kqx2QJrviVfpMUDn8',
    appId: '1:160463287371:android:dd6d52db5e7ac5b11989ce',
    messagingSenderId: '160463287371',
    projectId: 'dayzoff-c2455',
    storageBucket: 'dayzoff-c2455.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCwzqouGh6Nmmv1lYD2opRiEwi8juhfBw',
    appId: '1:160463287371:ios:813b934d4af101f81989ce',
    messagingSenderId: '160463287371',
    projectId: 'dayzoff-c2455',
    storageBucket: 'dayzoff-c2455.appspot.com',
    iosBundleId: 'com.example.dayzoff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCwzqouGh6Nmmv1lYD2opRiEwi8juhfBw',
    appId: '1:160463287371:ios:a496100e135bdfbf1989ce',
    messagingSenderId: '160463287371',
    projectId: 'dayzoff-c2455',
    storageBucket: 'dayzoff-c2455.appspot.com',
    iosBundleId: 'com.example.dayzoff.RunnerTests',
  );
}
